### ISSUE TITLE
Error in mcfork() :    unable to fork, possible reason: Cannot allocate memory

### ISSUE THREAD

**Issue by fentouxungui** [jooslee/ISLE#1]
bellow is what I got when i running  source isle.r.
```
>source('/data0/zhangyc/Data/WeiRX/cBioPortal/ISLE/data/ISLE-master/R/isle.r')
here
here
Error in mcfork() : 
  unable to fork, possible reason: Cannot allocate memory
In addition: There were 50 or more warnings (use warnings() to see the first 50)
```
My machine has 250G RAM, not enough?

**Comment by jooslee** [comment]
Hi, sorry for my late response. did not know that github has this feature due to my ignorance... we ran the code with 500GB. 250GB may not be sufficient for genome-wide SL identification. if you are limited by 250GB memory, you can run the isle.pairs.r for subset of gene pairs and then combine the results all together. note that the FDR should be done at each step for all candidate pairs. thanks, Joo
